# Generated by Django 4.2.9 on 2026-01-02 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "package_type",
                    models.CharField(
                        choices=[
                            ("adventure", "Adventure"),
                            ("beach", "Beach"),
                            ("cultural", "Cultural"),
                            ("family", "Family"),
                            ("honeymoon", "Honeymoon"),
                            ("pilgrimage", "Pilgrimage"),
                            ("wildlife", "Wildlife"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "duration_nights",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                ("includes_hotel", models.BooleanField(default=True)),
                ("includes_transport", models.BooleanField(default=True)),
                ("includes_meals", models.BooleanField(default=True)),
                ("includes_sightseeing", models.BooleanField(default=True)),
                ("includes_guide", models.BooleanField(default=False)),
                ("breakfast_included", models.BooleanField(default=True)),
                ("lunch_included", models.BooleanField(default=False)),
                ("dinner_included", models.BooleanField(default=False)),
                ("max_group_size", models.IntegerField(default=10)),
                ("min_group_size", models.IntegerField(default=2)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "destination_cities",
                    models.ManyToManyField(related_name="packages", to="core.city"),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="PackageInclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("is_included", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inclusions",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_included", "description"],
            },
        ),
        migrations.CreateModel(
            name="PackageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="packages/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="packages.package",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PackageItinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "activities",
                    models.TextField(help_text="Comma-separated list of activities"),
                ),
                (
                    "meals_included",
                    models.CharField(
                        blank=True, help_text="e.g., Breakfast, Lunch", max_length=100
                    ),
                ),
                ("accommodation", models.CharField(blank=True, max_length=200)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "ordering": ["package", "day_number"],
                "unique_together": {("package", "day_number")},
            },
        ),
        migrations.CreateModel(
            name="PackageDeparture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("departure_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "available_slots",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departures",
                        to="packages.package",
                    ),
                ),
            ],
            options={
                "ordering": ["departure_date"],
                "unique_together": {("package", "departure_date")},
            },
        ),
    ]
