# Generated by Django 4.2.9 on 2026-01-02 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "star_rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Star"),
                            (3, "3 Star"),
                            (4, "4 Star"),
                            (5, "5 Star"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "review_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("has_wifi", models.BooleanField(default=True)),
                ("has_parking", models.BooleanField(default=False)),
                ("has_pool", models.BooleanField(default=False)),
                ("has_gym", models.BooleanField(default=False)),
                ("has_restaurant", models.BooleanField(default=False)),
                ("has_spa", models.BooleanField(default=False)),
                ("has_ac", models.BooleanField(default=True)),
                ("checkin_time", models.TimeField(default="14:00")),
                ("checkout_time", models.TimeField(default="11:00")),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotels",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-review_rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Room"),
                            ("deluxe", "Deluxe Room"),
                            ("suite", "Suite"),
                            ("family", "Family Room"),
                            ("executive", "Executive Room"),
                        ],
                        default="standard",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("max_occupancy", models.IntegerField(default=2)),
                ("number_of_beds", models.IntegerField(default=1)),
                (
                    "room_size",
                    models.IntegerField(
                        blank=True, help_text="Size in square feet", null=True
                    ),
                ),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("has_balcony", models.BooleanField(default=False)),
                ("has_tv", models.BooleanField(default=True)),
                ("has_minibar", models.BooleanField(default=False)),
                ("has_safe", models.BooleanField(default=False)),
                ("total_rooms", models.IntegerField(default=1)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="hotels/rooms/"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_types",
                        to="hotels.hotel",
                    ),
                ),
            ],
            options={
                "ordering": ["hotel", "base_price"],
            },
        ),
        migrations.CreateModel(
            name="HotelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotels/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="hotels.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("available_rooms", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="hotels.roomtype",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("room_type", "date")},
            },
        ),
    ]
