# Generated by Django 4.2.9 on 2026-01-02 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="gst_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="GST percentage (default: 18%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
