# Generated by Django 4.2.9 on 2026-01-02 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bus_number", models.CharField(max_length=50, unique=True)),
                ("bus_name", models.CharField(max_length=200)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("seater", "Seater"),
                            ("sleeper", "Sleeper"),
                            ("semi_sleeper", "Semi-Sleeper"),
                            ("ac_seater", "AC Seater"),
                            ("ac_sleeper", "AC Sleeper"),
                            ("volvo", "Volvo"),
                            ("luxury", "Luxury"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "total_seats",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("has_ac", models.BooleanField(default=False)),
                ("has_wifi", models.BooleanField(default=False)),
                ("has_charging_point", models.BooleanField(default=False)),
                ("has_blanket", models.BooleanField(default=False)),
                ("has_water_bottle", models.BooleanField(default=False)),
                ("has_tv", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["operator", "bus_number"],
            },
        ),
        migrations.CreateModel(
            name="BusOperator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="buses/operators/"
                    ),
                ),
                ("contact_phone", models.CharField(max_length=20)),
                ("contact_email", models.EmailField(max_length=254)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("route_name", models.CharField(max_length=200)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("duration_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=7)),
                ("base_fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("operates_monday", models.BooleanField(default=True)),
                ("operates_tuesday", models.BooleanField(default=True)),
                ("operates_wednesday", models.BooleanField(default=True)),
                ("operates_thursday", models.BooleanField(default=True)),
                ("operates_friday", models.BooleanField(default=True)),
                ("operates_saturday", models.BooleanField(default=True)),
                ("operates_sunday", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="buses.bus",
                    ),
                ),
                (
                    "destination_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_routes_to",
                        to="core.city",
                    ),
                ),
                (
                    "source_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_routes_from",
                        to="core.city",
                    ),
                ),
            ],
            options={
                "ordering": ["source_city", "destination_city", "departure_time"],
            },
        ),
        migrations.AddField(
            model_name="bus",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buses",
                to="buses.busoperator",
            ),
        ),
        migrations.CreateModel(
            name="SeatLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("seater", "Seater"),
                            ("sleeper_lower", "Sleeper Lower"),
                            ("sleeper_upper", "Sleeper Upper"),
                        ],
                        max_length=20,
                    ),
                ),
                ("row", models.IntegerField()),
                ("column", models.IntegerField()),
                ("deck", models.IntegerField(default=1)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_layout",
                        to="buses.bus",
                    ),
                ),
            ],
            options={
                "ordering": ["deck", "row", "column"],
                "unique_together": {("bus", "seat_number")},
            },
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_name", models.CharField(max_length=200)),
                ("stop_order", models.IntegerField()),
                ("arrival_time", models.TimeField()),
                ("departure_time", models.TimeField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.city"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "stop_order"],
                "unique_together": {("route", "stop_order")},
            },
        ),
        migrations.CreateModel(
            name="BusSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("available_seats", models.IntegerField()),
                ("fare", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("route", "date")},
            },
        ),
    ]
