# Generated by Django 4.2.9 on 2026-01-02 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buses", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="busoperator",
            options={"ordering": ["-rating", "name"]},
        ),
        migrations.AddField(
            model_name="bus",
            name="average_rating",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="chassis_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_cctv",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_emergency_exit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_first_aid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_gps_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bus",
            name="has_reading_light",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bus",
            name="manufacturing_year",
            field=models.IntegerField(
                blank=True, help_text="Year of manufacturing", null=True
            ),
        ),
        migrations.AddField(
            model_name="bus",
            name="registration_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="bus",
            name="total_reviews",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="business_license",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="gst_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="registered_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="total_bookings",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="total_trips_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bus_operator_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Verification"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="busoperator",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_operators",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="busschedule",
            name="booked_seats",
            field=models.IntegerField(default=0, help_text="Seats already booked"),
        ),
        migrations.AddField(
            model_name="busschedule",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="busschedule",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="busschedule",
            name="window_seat_charge",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="available_seats",
            field=models.IntegerField(help_text="Seats currently available"),
        ),
        migrations.AlterField(
            model_name="busschedule",
            name="fare",
            field=models.DecimalField(
                decimal_places=2, help_text="Dynamic pricing per seat", max_digits=10
            ),
        ),
        migrations.CreateModel(
            name="DroppingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="e.g., Koyambedu, CMBT", max_length=200),
                ),
                ("address", models.TextField()),
                (
                    "landmark",
                    models.CharField(
                        blank=True, help_text="Nearby landmark", max_length=200
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("drop_time", models.TimeField(help_text="Drop time at this point")),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "sequence_order",
                    models.IntegerField(default=1, help_text="Order of drop points"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.city"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dropping_points",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "sequence_order", "drop_time"],
                "unique_together": {("route", "name")},
            },
        ),
        migrations.CreateModel(
            name="BoardingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Majestic Bus Stand, Electronic City",
                        max_length=200,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "landmark",
                    models.CharField(
                        blank=True, help_text="Nearby landmark", max_length=200
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "pickup_time",
                    models.TimeField(help_text="Pickup time at this point"),
                ),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                (
                    "sequence_order",
                    models.IntegerField(default=1, help_text="Order of pickup points"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.city"
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boarding_points",
                        to="buses.busroute",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "sequence_order", "pickup_time"],
                "unique_together": {("route", "name")},
            },
        ),
    ]
