# Generated by Django 4.2.9 on 2026-01-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buses", "0002_alter_busoperator_options_bus_average_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatlayout",
            name="reserved_for",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("ladies", "Ladies Only"),
                    ("disabled", "Disabled"),
                ],
                default="general",
                help_text="Reserve seats for specific passenger types",
                max_length=20,
            ),
        ),
    ]
